### PR TITLE
Added Fr./CHF, fixes #14

### LINKED ISSUE #14: May we have CHF as well?
This would be great. Thanks in advance.

### PR DESCRIPTION
**Pull request by philippeowagner**
In addition I changed the order of the currency list. Not sure it the order has an impact to other parts of the code/app.

### CODE REVIEW

**Comment by vinniejames** [comment]
HUGE thanks for being the first contributor!

**Comment by vinniejames** [comment]
Please revert the package-lock.json changes

**Comment by philippeowagner** [comment]
Reverted as requested.

**Comment by vinniejames** [comment]
Merging in to test and deploy, thanks man. If you have any objections to the [GNU license](https://github.com/vinniejames/coinfox/blob/master/LICENSE.md), send me a message and ill revert this PR.

Cheers!

**Pull request merged**
